apiVersion: apps/v1
kind: Deployment
metadata:
  name: joker
spec:
  replicas: 4
  template:
    spec:
      containers:
      - name: joker
        image: gcr.io/aramse-training/my-joker-app:1.0
        resources:
          requests:
            cpu: 0.1
        readinessProbe:
          httpGet:
            path: /health
            port: 80

---
apiVersion: v1
kind: Service
metadata:
  name: joker-<MY_NAME>
spec:
  ports:
  - name: port80
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: joker-<MY_NAME>
  type: LoadBalancer
